### ISSUE TITLE
The link to download is empty

### ISSUE THREAD

**Issue by SarraCode** [owo/madamira_diac#1]
Hello,
Thank you for your contributions. I was looking for a working link to get the software but this link http://innovation.columbia.edu/technologies/cu14012_arabic-language-disambiguation-for-natural-language-processing-applications open an empty page.

Thank you in advance
@owo

**Comment by owo** [comment]
Hi @SarraCode,

That is odd. I just tried the link and it works, although it does take a couple of seconds to load.
What browser/OS/device are you trying on?

**Comment by SarraCode** [comment]
![image](https://user-images.githubusercontent.com/73901891/99548477-fb31d380-29b8-11eb-9f19-6ca8dc0b2bbd.png)
Wierd, it worked when I tried now on another laptop (ubuntu) but not working on mac os for the same browser (screenshot joined). Thank you for the quick response.

**Comment by owo** [comment]
No worries :)
